ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

if ENV['VAGRANT_CLIENT_COUNT']
VAGRANT_CLIENT_COUNT = ENV['VAGRANT_CLIENT_COUNT']
else
VAGRANT_CLIENT_COUNT = 3
end

Vagrant.configure("2") do |config|

  config.vm.define "dhcp1" do |dhcp1|
    dhcp1.vm.box = "ubuntu/focal64"
    dhcp1.vm.network "private_network", ip:"192.168.56.100", netmask:"255.255.255.0"
    dhcp1.vm.hostname = "dhcp1"
    dhcp1.vm.provision "shell", path: "dhcp1.sh"
  end

  (1..VAGRANT_CLIENT_COUNT.to_i).each do |i|
      config.vm.define "client#{i+1}" do |client|
        client.vm.box = "ubuntu/focal64"
        client.vm.network "private_network", type: "dhcp"
        client.vm.hostname = "client#{i+1}"
        end
      end

end