Vagrant.configure("2") do |config|
  #config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "dhcp1" do |dhcp1|
    dhcp1.vm.box = "ubuntu/focal64"
    dhcp1.vm.network "private_network", ip:"192.168.56.100", netmask:"255.255.255.0"
    dhcp1.vm.hostname = "dhcp1"
    dhcp1.vm.provision "shell", path: "dhcp1.sh"
  end

  config.vm.define "client2" do |client2|
    client2.vm.box = "ubuntu/focal64"
    client2.vm.network "private_network", type: "dhcp"
    client2.vm.hostname = "client2"
  end

  config.vm.define "client3" do |client3|
    client3.vm.box = "ubuntu/focal64"
    client3.vm.network "private_network", type: "dhcp"
    client3.vm.hostname = "client3"
  end

  config.vm.define "client4" do |client4|
    client4.vm.box = "ubuntu/focal64"
    client4.vm.network "private_network", type: "dhcp"
    client4.vm.hostname = "client4"
  end

end