Resources:

  S3bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketName: tfstate-bucket-katroo
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  TerraformStateLockDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tfstate-lock-ddb
        AttributeDefinitions:
          - AttributeName: LockID
            AttributeType: S
        KeySchema:
          - AttributeName: LockID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        SSESpecification:
          SSEEnabled: true