version: '3'
services:
  web:
    image: trafex/php-nginx
    ports:
      - "${APP_PORT}:8080"
    volumes:
      - ./php-mysql-crud:/var/www/html
    networks:
      - app-network
  db:
    image: mysql
    ports:
      - "${DB_PORT}:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./php-mysql-crud/database:/docker-entrypoint-initdb.d
      - ./datadir:/var/lib/mysql
    networks:
      - app-network
networks:
    app-network:
      driver: bridge